package parser

const (
	AccPublic       = 0x0001 //Declared public; may be accessed from outside its package.
	AccPrivate      = 0x0002 //Declared private; usable only within the defining class.
	AccProtected    = 0x0004 //Declared protected; may be accessed within subclasses.
	AccStatic       = 0x0008 //Declared static.
	AccFinal        = 0x0010 //Declared final; never directly assigned to after object construction.
	AccSynchronized = 0x0020 //Declared synchronized; invocation is wrapped by a monitor use.
	AccSuper        = 0x0020 //Treat superclass methods specially when invoked by the invokespecial instruction.
	AccBridge       = 0x0040 //A bridge method, generated by the compiler.
	AccVolatile     = 0x0040 //Declared volatile; cannot be cached.
	AccVarArgs      = 0x0080 //Declared with variable number of arguments.
	AccTransient    = 0x0080 //Declared transient; not written or read by a persistent object manager.
	AccNative       = 0x0100 //Declared native; implemented in a language other than Java.
	AccInterface    = 0x0200 //Is an interface, not a class.
	AccAbstract     = 0x0400 //Declared abstract; no implementation is provided.
	AccStrict       = 0x0800 //Declared strictfp; floating-point mode is FP-strict.
	AccSynthetic    = 0x1000 //Declared synthetic; not present in the source code.
	AccAnnotation   = 0x2000 //Declared as an annotation type.
	AccEnum         = 0x4000 //Declared as an element of an enum.
)
