package parser

const (
	accPublic       = 0x0001 //Declared public; may be accessed from outside its package.
	accPrivate      = 0x0002 //Declared private; accessible only within the defining class.
	accProtected    = 0x0004 //Declared protected; may be accessed within subclasses.
	accStatic       = 0x0008 //Declared static.
	accFinal        = 0x0010 //Declared final; no subclasses allowed.
	accSynchronized = 0x0020 //Declared synchronized; invocation is wrapped by a monitor use.
	accSuper        = 0x0020 //Treat superclass methods specially when invoked by the invokespecial instruction.
	accBridge       = 0x0040 //A bridge method, generated by the compiler.
	accVarArgs      = 0x0080 //Declared with variable number of arguments.
	accNative       = 0x0100 //Declared native; implemented in a language other than Java.
	accInterface    = 0x0200 //Is an interface, not a class.
	accAbstract     = 0x0400 //Declared abstract; must not be instantiated.
	accStrict       = 0x0800 //Declared strictfp; floating-point mode is FP-strict.
	accSynthetic    = 0x1000 //Declared synthetic; not present in the source code.
	accAnnotation   = 0x2000 //Declared as an annotation type.
	accEnum         = 0x4000 //Declared as an enum type.
)
